FROM alpine:3.9

RUN apk --no-cache upgrade && \
  apk add --no-cache git wget unzip npm curl && \
  apk add --no-cache chromium nodejs && \
  curl -L -O https://github.com/getgauge/gauge/releases/download/v1.0.5/gauge-1.0.5-linux.x86_64.zip && \
  unzip -o gauge-1.0.5-linux.x86_64.zip -d /usr/local/bin

ADD docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
