FROM ubuntu:trusty

RUN apt-get update && \
    apt-get install -y git wget unzip npm curl && \
    apt-get install -y chromium-browser libgconf-2-4 && \
    curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && \
    ln -s $(which nodejs) /usr/local/bin/node && \
    wget https://github.com/getgauge/gauge/releases/download/v0.9.7/gauge-0.9.7-linux.x86_64.zip && \
    unzip -o gauge-0.9.7-linux.x86_64.zip -d /usr/local/bin && \
    apt-get -y autoremove

ADD docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
