FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y git nodejs && \
    apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B && \
    echo deb https://dl.bintray.com/gauge/gauge-deb stable main | tee -a /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y gauge chromium-browser libgconf-2-4 && \
    apt-get -y autoremove

ADD docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
